### ISSUE TITLE
Allow custom AWS regions

### ISSUE THREAD

**Issue by ranjan-purbey** [YoyaTeam/dynamodb-manager#14]
When mocking an API using AWS amplify-cli, the dynamodb-local database that is created uses the region "us-fake-1". But dynamodb-manager doesn't allow to set such custom regions in the database config. It would be great if that was allowed.

**Comment by taydy** [comment]
Sorry i didn't notice your issue in time. So The first time I fixed this problem, when I saw this issure. Now you can use custom AWS regions. Thank you very much for your suggestion

**Comment by ranjan-purbey** [comment]
Thanks @taydy
