### ISSUE TITLE
Please add one kind of query support!

### ISSUE THREAD

**Issue by bruce121** [YoyaTeam/dynamodb-manager#4]
This tool is very easy to use.
I think the function can add a `begins_with (a, substr)` query support.
According to the document of AWS dynamodb, the link is on below
[https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html)
![query](https://user-images.githubusercontent.com/28733276/48758691-e217be80-ecdb-11e8-8bd6-4348dbee0c39.png)

**Comment by taydy** [comment]
Thank you for your issue!We have now added all supported filters
