### ISSUE TITLE
Pagination issues!

### ISSUE THREAD

**Issue by bruce121** [YoyaTeam/dynamodb-manager#5]
Pagination issues, 
I stored a relatively large item in DynamoDb.(about 230KB/item)
Base on the query of DynamoDb supported, only 1MB data returned, so the first page shows 0 - 5, and what I expected is 6 - 10 on the second page but got 100 - 105, and the third page shows 200 - 205.
In this case, I can`t get the total number of items by turning the page.

**Comment by taydy** [comment]
We have fixed this issue in the latest code.Thank you for your issue!
