### ISSUE TITLE
Error "Configuration is not in effect"

### ISSUE THREAD

**Issue by shashikantkulkarni** [YoyaTeam/dynamodb-manager#9]
Hello,

I am trying to use this tool. I am able to run it and see the UI but when I try to add a connection to connect to local dynamodb then while applying the configuration I get an error as "Configuration is not in effect". Local dynamodb instance is running on localhost on port 8000. Please let me know how to fix this error and apply the configuration.
<img width="1280" alt="Screenshot 2019-10-30 at 11 16 42 PM" src="https://user-images.githubusercontent.com/4160148/67884256-88ff0e80-fb6b-11e9-9ce1-2d8f6e6edc6f.png">

Thank you in advance.
Regards,
Shashikant

**Comment by taydy** [comment]
hi, Did you set the -cors parameter when starting local dynamodb?

**Comment by taydy** [comment]
Please let me know if your problem has been resolved.

**Comment by shashikantkulkarni** [comment]
No I didn’t set the -cors parameter. Let me try with that. I will update
you.
Thanks.

**Comment by shashikantkulkarni** [comment]
Hello,
It is working as per your suggestion. Thank you.
Can you please add it in your documentation so it will help others if they face this issue.

Thanks once again.

**Comment by taydy** [comment]
Very happy to help you

**Comment by timothyjeffcoat** [comment]
Another way to overcome CORS trouble is to set the environment variable like

**Comment by Ventzy** [comment]
`DISABLE_CORS_CHECKS=1` does not seems to be working. I am running `docker run -t --env DISABLE_CORS_CHECKS=1 -p 8080:80 taydy/dynamodb-manager` but I am still getting the error and I see cors issue in Chrome's network tab. Any other solution?

**Comment by First-Met** [comment]
hi  how to reslove this issue? thanks
I have set the Param "- cors *",but didn't resloved.
java -jar DynamoDBLocal.jar -sharedDb -cors '*' -dbPath ./data -port 8001
Port:   8001
InMemory:       false
DbPath: ./data
SharedDb:       true
shouldDelayTransientStatuses:   false
CorsParams:     *



![image](https://user-images.githubusercontent.com/25097285/200106724-c14a7192-7d53-464f-ac47-86e4c1210111.png)

**Comment by prashantchandrap-sportsbet** [comment]
If you are running docker and exposing port 80 of docker to 8001, then you have to run below:
`java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb -cors http://localhost:8001`

Which will result:

`Initializing DynamoDB Local with the following configuration:`
`Port:	8000`
`InMemory:	false`
`DbPath:	null`
`SharedDb:	true`
`shouldDelayTransientStatuses:	false`
`CorsParams:	http://localhost:8001`

And then you'll access Dynamodb Manager in your browser via `http://localhost:8001/`

**Comment by ArchanaNeog** [comment]
Cors setup in local DynamoDB running in docker
We can set the cors while running the docker instance as shown below
docker run --name dynamodb -p 8000:8000 amazon/dynamodb-local -jar DynamoDBLocal.jar -cors http://localhost:8080

Initializing DynamoDB Local with the following configuration:
Port:   8000
InMemory:       false
DbPath: null
SharedDb:       false
shouldDelayTransientStatuses:   false
CorsParams:     http://localhost:8080

**Comment by Stephen0910** [comment]
Is there any other way to solve the problem?
dynamodb is not deployed by me, so I can't change its parameters
Also, it seems that the 2.x version of dynamodb doesn't work even after changing it
Is it possible to access dynamodb without changing its environment parameters, but only changing the content of the project?
Best wishes.

**Comment by Stephen0910** [comment]
> Is there any other way to solve the problem? dynamodb is not deployed by me, so I can't change its parameters Also, it seems that the 2.x version of dynamodb doesn't work even after changing it Is it possible to access dynamodb without changing its environment parameters, but only changing the content of the project? Best wishes.

by the way, I can directly connect the dynamodb server by cmd: aws dynamodb get-item --table-name...
So I think this is a bug should be fixed in dynamodb-manager.

**Comment by Stephen0910** [comment]
I recommend another option to solve the cross-domain problem using a browser plugin.
https://chromewebstore.google.com/detail/cross-domain-cors/mjhpgnbimicffchbodmgfnemoghjakai

**Comment by z-krish** [comment]
> ase let me know how to fix

if your dynamo is running in 8000, why cors of 8080 should be done?
